# Generated by Django 6.0.4 on 2026-07-05 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=255)),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='RUNNING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execution Log',
                'verbose_name_plural': 'Execution Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
